/**********************************************************
 * This file is generated by the 20-sim C++ Code Generator
 *
 *  file:  ControllerTilt.h
 *  subm:  ControllerTilt
 *  model: ControllerTilt
 *  expmt: Jiwy-with-controller
 *  date:  March 30, 2023
 *  time:  12:00:10 PM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 *
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the ControllerTilt.cpp file
*/
#ifndef ControllerTilt_H
#define ControllerTilt_H

/* 20-sim include files */
#include "common/xxfuncs.h"
#include "common/xxmatrix.h"
#include "common/xxmodel.h"
#include "common/xxinteg.h"

class ControllerTilt : virtual public Submodel20sim
{
public:
    enum stateflags_ControllerTilt
    {
        initialrun,
        mainrun,
        finished
    };
    ControllerTilt(void);
    virtual ~ControllerTilt(void);
    void Initialize(XXDouble *u, XXDouble *y, XXDouble t);
    void Calculate(XXDouble *u, XXDouble *y /*, XXDouble t*/);
    void Terminate(XXDouble *u, XXDouble *y /*, XXDouble t*/);
    bool SetFinishTime(XXDouble newtime);
    bool IsFinished(void);
    void Reset(XXDouble starttime);
    stateflags_ControllerTilt state;

protected:
    void CalculateDynamic(void);

private:
    void CalculateInitial(void);
    void CalculateStatic(void);
    void CalculateInput(void);
    void CalculateOutput(void);
    void CalculateFinal(void);
    void CopyInputsToVariables(XXDouble *u);
    void CopyVariablesToOutputs(XXDouble *y);
    Euler myintegmethod;
};
