/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\EulerAngles.h
 *  model: ControllerTilt
 *  expmt: Jiwy-with-controller
 *  date:  March 30, 2023
 *  time:  12:00:10 PM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/*****************************************************************************
--------------------------------------------------------------------------

 Copyright � 1995-2007 Controllab Products B.V. All Rights Reserved.

             www.controllab.nl
               www.20sim.com

 Authors: Frank Groen
--------------------------------------------------------------------------
 Description:

 Contains code for converting between different angle representations
 all 24 different kind of Euler angles
 Quaternions and H-Matrices and Rotation Matrices
--------------------------------------------------------------------------
******************************************************************************/

