/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  ControllerTilt
 *  model: ControllerTilt
 *  expmt: Jiwy-with-controller
 *  date:  March 30, 2023
 *  time:  12:00:10 PM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


